name: chat_proto
description: "chat model and service base classes"
version: 0.0.2
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  grpc: ^3.2.4
  objectbox: ^4.0.1
  protobuf: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  objectbox_generator:
