name: chat_proto
description: "chat model and service base classes"
version: 0.0.9
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  grpc: ^3.2.4
  protobuf: ^3.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  